const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
function setup(user,options={}){const calls=[],sql=async(strings,...values)=>{const text=strings.join('?').replace(/\s+/g,' ').trim();calls.push({text,values});if(text.startsWith('SELECT id FROM users'))return {rows:options.found||[{id:1}]};if(text.startsWith('DELETE FROM users')){if(options.fail)throw Error('write failed');return {rows:[{id:1}]};}if(text.startsWith('SELECT COUNT'))return {rows:[{total:1,students:1,teachers:0,tests:1}]};return {rows:[]};};const client={sql,query:async text=>calls.push({text}),release:()=>calls.push({text:'RELEASE'})};sql.connect=async()=>client;const module={exports:{}},res={code:200,status(code){this.code=code;return this;},json(body){this.body=body;return this;}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../api/principal/accounts.js'),'utf8'),{module,require:id=>({'../../lib/db':{sql,ensureSchema:async()=>{}},'../../lib/auth':{requireAuth:async(req,res)=>{if(user?.role!=='principal'){res.status(403).json({});return null;}return user;}}}[id]),console,Number,String,Array,Set,JSON,Promise});return {calls,res,run:(method,body={},query={})=>module.exports({method,body,query},res)};}
test('Only principal may manage accounts',async()=>{for(const role of ['student','teacher'])for(const method of ['GET','PATCH','DELETE']){const s=setup({id:1,role});await s.run(method);assert.equal(s.res.code,403);assert.equal(s.calls.length,0);}});
test('Listing excludes protected identities and never selects password hashes',async()=>{const s=setup({id:0,role:'principal',username:'admin'});await s.run('GET',{}, {page:'2',q:'test',role:'student',test:'true'});assert.equal(s.res.code,200);assert.ok(s.calls.every(c=>c.text.includes("role IN ('student','teacher')")&&c.text.includes('id<>')));assert.ok(s.calls[0].text.includes('LIMIT 25 OFFSET'));assert.ok(s.calls[0].values.includes(25));assert.ok(!s.calls[0].text.includes('password'));});
test('Deleting requires exact confirmation, positive IDs and a bounded selection',async()=>{for(const body of [{ids:[0],confirmation:'حذف الحسابات المحددة'},{ids:[1],confirmation:'yes'},{ids:[1.5],confirmation:'حذف الحسابات المحددة'},{ids:Array(51).fill(1),confirmation:'حذف الحسابات المحددة'}]){const s=setup({id:0,role:'principal'});await s.run('DELETE',body);assert.equal(s.res.code,400);assert.equal(s.calls.length,0);}});
test('Deletion is atomic and preserves published laws and questions',async()=>{const s=setup({id:0,role:'principal'});await s.run('DELETE',{ids:[1],confirmation:'حذف الحسابات المحددة'});assert.equal(s.res.body.deleted,1);assert.ok(s.calls.some(c=>c.text==='BEGIN'));assert.ok(s.calls.some(c=>c.text==='COMMIT'));assert.ok(s.calls.some(c=>c.text.startsWith('DELETE FROM learning_question_reports')));assert.ok(!s.calls.some(c=>c.text.includes('teacher_laws')||c.text.includes('DELETE FROM questions')));assert.equal(s.calls.at(-1).text,'RELEASE');});
test('Missing or protected selections cannot cause partial deletion',async()=>{const s=setup({id:0,role:'principal'},{found:[]});await s.run('DELETE',{ids:[1],confirmation:'حذف الحسابات المحددة'});assert.equal(s.res.code,404);assert.ok(!s.calls.some(c=>c.text.startsWith('DELETE')));assert.ok(s.calls.some(c=>c.text==='ROLLBACK'));});
test('Failed writes roll back and release the database connection',async()=>{const s=setup({id:0,role:'principal'},{fail:true});await s.run('DELETE',{ids:[1],confirmation:'حذف الحسابات المحددة'});assert.equal(s.res.code,500);assert.ok(s.calls.some(c=>c.text==='ROLLBACK'));assert.ok(!s.calls.some(c=>c.text==='COMMIT'));assert.equal(s.calls.at(-1).text,'RELEASE');});
test('Test-account labels require a boolean and protect principal identity',async()=>{const s=setup({id:0,role:'principal'});await s.run('PATCH',{id:1,isTest:'true'});assert.equal(s.res.code,400);await s.run('PATCH',{id:1,isTest:true});assert.ok(s.calls[0].text.includes('role IN'));assert.ok(s.calls[0].text.includes('id<>'));});
test('Deleted student and teacher tokens are rejected on every authenticated request',async()=>{for(const role of ['student','teacher']){const module={exports:{}},res={code:200,status(code){this.code=code;return this;},json(){return this;}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../lib/auth.js'),'utf8'),{module,process:{env:{JWT_SECRET:'test-secret'}},require:id=>id==='bcryptjs'?{}:id==='jsonwebtoken'?{verify:()=>({id:1,role})}:{sql:async()=>({rows:[]})}});assert.equal(await module.exports.requireAuth({headers:{authorization:'Bearer test'}},res),null);assert.equal(res.code,401);}});
