const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const validation=require('../lib/laws');
const law={track:'qudrat',subject:'quant',title:'قانون السرعة',formula:'السرعة = المسافة ÷ الزمن',explanation:'',example:'',source:'',clientKey:'law-test-1234'};
function setup(user,rows=[]){const calls=[],sql=async(strings,...values)=>{calls.push({text:strings.join('?'),values});return {rows};},module={exports:{}};const res={code:200,body:null,status(code){this.code=code;return this;},json(body){this.body=body;return this;}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../api/laws.js'),'utf8'),{module,require:id=>({'../lib/db':{sql,ensureSchema:async()=>{}},'../lib/auth':{requireAuth:async(req,res,role)=>{if(!user){res.status(401).json({});return null;}if(role==='teacher'&&!['teacher','principal'].includes(user.role)){res.status(403).json({});return null;}return user;}},'../lib/laws':validation}[id])});return {calls,res,run:(method,body={},query={})=>module.exports({method,body,query},res)};}
test('Law validation requires valid subject, title and formula',()=>{for(const update of [{track:'unknown'},{subject:'bio'},{title:' '},{formula:''},{title:'x'.repeat(161)},{formula:{}},{example:'x'.repeat(4001)}])assert.throws(()=>validation.validateLaw({...law,...update}));assert.equal(validation.validateLaw({...law,title:' عنوان '}).title,'عنوان');});
test('Students cannot create, edit or delete laws',async()=>{for(const method of ['POST','PUT','DELETE']){const s=setup({id:1,role:'student'});await s.run(method,{...law,id:2},{id:2});assert.equal(s.res.code,403);assert.equal(s.calls.length,0);}});
test('Law reads require authentication',async()=>{const s=setup(null);await s.run('GET');assert.equal(s.res.code,401);assert.equal(s.calls.length,0);});
test('Student reads expose text but not editing rights or internal save keys',async()=>{const s=setup({id:1,role:'student'},[{...law,id:7,owner_id:1,owner_name:'معلمة'}]);await s.run('GET');assert.equal(s.res.body.laws[0].canEdit,false);assert.equal(s.res.body.laws[0].clientKey,undefined);assert.equal(s.res.body.laws[0].author,'معلمة');});
test('Repeated saves use unique owner/client key',async()=>{const s=setup({id:2,role:'teacher'},[{...law,id:7,owner_id:2}]);await s.run('POST',law);assert.equal(s.res.code,200);assert.ok(s.calls[0].text.includes('ON CONFLICT(owner_id,client_key)'));assert.equal(s.res.body.law.canEdit,true);assert.equal(s.calls[0].values[0],2);});
test('Editing and deletion enforce owner/principal restrictions in SQL',async()=>{for(const method of ['PUT','DELETE']){const s=setup({id:2,role:'teacher'});await s.run(method,{...law,id:7},{id:7});assert.equal(s.res.code,404);assert.ok(s.calls[0].text.includes('owner_id='));assert.ok(s.calls[0].values.includes(2));}});
test('Principal may edit laws by other teachers',async()=>{const s=setup({id:0,role:'principal'},[{...law,id:7,owner_id:2}]);await s.run('PUT',{...law,id:7});assert.equal(s.res.code,200);assert.equal(s.res.body.law.canEdit,true);assert.ok(s.calls[0].values.includes('principal'));});
test('Malformed IDs and fields are rejected before SQL writes',async()=>{for(const id of [0,-1,'abc',2.5]){const s=setup({id:2,role:'teacher'});await s.run('DELETE',{}, {id});assert.equal(s.res.code,400);assert.equal(s.calls.length,0);}const s=setup({id:2,role:'teacher'});await s.run('POST',{...law,clientKey:'x'});assert.equal(s.res.code,400);assert.equal(s.calls.length,0);});
